name: Bicep / Automaticly Triggered ARM Generation

on:
  push:
    branches-ignore:
      - main
    paths:
      - Environments/**/*.bicep
      - Environments/**/manifest.yaml

env:
  APPLICATION_DIRECTORY: Environments/Unreal-Cloud-DDC

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      my-key: ${{ steps.my-key.outputs.defined }}
    steps:
      - id: my-key
        if: "${{ env.MY_KEY != '' }}"
        run: echo "defined=true" >> $GITHUB_OUTPUT
        env:
          MY_KEY: ${{ secrets.PAT }}

  get-module-to-validate:
    needs: [check-secret]
    if: needs.check-secret.outputs.my-key == 'true'
    uses: ./.github/workflows/get-changed-module.yml

  push-bicep-generate:
    runs-on: ubuntu-latest
    needs: get-module-to-validate
    if: needs.get-module-to-validate.outputs.module_dir
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PAT }} # A PAT must be used to re-trigger workflows after commit. This PAT should NOT have the workflow scope.

      # Adding a step to explicitly install the latest Bicep CLI because there is
      # always a delay in updating Bicep CLI in the job runner environments.
      - name: Install the latest Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version

      - name: Generate ARM template from Bicep templates
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: "${{ env.APPLICATION_DIRECTORY }}/mainTemplate.bicep"
          outputFilePath: "${{ env.APPLICATION_DIRECTORY }}/azuredeploy.json"

      - uses: EndBug/add-and-commit@v9
        with:
          message: Autogenerate Bicep Files
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: Environments
